[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "leb128"
version = "0.2.1"

description = "Read and write DWARF's \"Little Endian Base 128\" (LEB128) variable length integer encoding."

license = "Apache-2.0/MIT"
readme = "./README.md"
keywords = ["LEB128", "DWARF", "variable", "length", "encoding"]
documentation = "http://fitzgen.github.io/leb128/leb128/index.html"
repository = "https://github.com/fitzgen/leb128"

[dependencies]

# Unfortunately, clippy keeps breaking on recent nightlies. Disabling until it
# stabilizes a bit more.

# [dependencies.clippy]
# optional = true
# version = "0.0.76"

[features]
nightly = []
